### PR TITLE
Add microcode availability check to Verify-ESXiMicrocodePatch

### PR DESCRIPTION
**Pull request by adarobin**
Hi William,
I have extended the Verify-ESXiMicrocodePatch function to also check if the underlying CPU in the host has a microcode update available.

Unfortunately, I don't really have an official list of what CPUs currently have microcode updates available.  I also don't have a way of knowing what microcode updates VMware is actually shipping.  Maybe this is something you could help with?

The other issue is that I also don't have any AMD hardware to test with (or know anything about microcode availability from AMD for that matter).

### CODE REVIEW

**Comment by lamw** [comment]
Adam,

I really appreciate the feedback. I wanted to limit the scope of the script to help customers verify what's been outlined in the KB (as that's official guidance). I think the additional microcode logic can indeed be useful, can I suggest maybe you create a separate script that can be provide this functionality for those interested? You're more than welcome to contribute back to the repo. 

Thanks for understanding

**Comment by adarobin** [comment]
Hi @lamw ,
If I wanted to find out which CPUs VMware is providing microcode for, what is my best route?  A support request?  I posted a comment on the KB already.

**Comment by lamw** [comment]
@adarobin It looks like VMware just released a new KB (https://kb.vmware.com/s/article/52345) which outlines certain CPUs impacted by bad Microcode by Intel ... would like to see how we can adopt this function to match against the listed CPUs. It looks like you've already got the base code to check against "Encoded CPUID Family. Model. Stepping"

**Comment by adarobin** [comment]
@lamw I actually was working on a separate function to implement the microcode check I wanted.  I also figured out a way to get the CPU signature without using esxcli, so that its much faster.  I merged that work back into my original changes to Verify-ESXiMicrocodePatch and added a IntelSighting check too.

This is what I have now https://github.com/adarobin/vghetto-scripts/commit/8de4f6a3acf1ef2068ccfd92f30707c3720dba9a

I can remove the microcode availibility check as I assume you still don't want that functionality, but leave the IntelSighting stuff.  Let me know what you think.

**Comment by adarobin** [comment]
@lamw It would probably be useful to see what version of microcode is currently loaded if the system is impacted?  Unfortunately, the only place I have found to query that information is so far is vsish.
`
vsish -e cat /hardware/cpu/cpuList/0 | grep microcode -A 2
`

https://blogs.vmware.com/vsphere/2015/05/using-esxi-6-0-cpu-microcode-loading-feature.html
https://www.v-front.de/2015/05/cpu-microcode-updates-revisited-whats.html

**Comment by lamw** [comment]
@adarobin Great work! I figured there was a way to get the CPUID information w/o going to ESXCLI, but wasn't sure how to perform the translation, you just saved me a bunch of time. 

Yes, it would be great to add IntelSighting information (if you don't mind, could you provide pull request) OR I can just pull your code (will attribute of course).

In terms of the current microcode, will need to think on that and whether there's another option. I've also got the code to remediate against IntelSighting but wanted to make sure I had way to verify affected systems. Thanks for your help

**Comment by adarobin** [comment]
@lamw I found a couple logic errors, so I will fix those and then submit a pull request for just the IntelSighting stuff.

**Comment by lamw** [comment]
Thanks for pull request @adarobin I've verified it on the one system I've got and also asked fellow community member to verify as well. I've also updated the code to include CPU Model since that might help customers quickly figure out the CPUs they've got.

**Pull request closed without merging**
